Creacion de un vector para cada estudiante 

1. Vectores y Matrices
1.1
```{r}
Student_1 <- c(50.4,62.3,92.1,77.6,TRUE)
Student_2 <- c(41.7,87.9,75.3,72.4,FALSE)
Student_3 <- c(30.3,67.8,69.3,71.2,FALSE)
Student_4 <- c(65.4,85.1,92.3,96.8,TRUE)
Student_5 <- c(70.4,88.2,95.2,90.7,TRUE)
```
1.2
```{r}
student_vector <-c(Student_1,Student_2,Student_3,Student_4,Student_5)
student_vector
```
1.3
```{r}
student_matrix <- matrix(student_vector, byrow = TRUE, nrow = 5)
student_matrix
```
2.Nombrado de una matriz
2.1
```{r}

name_students <- c("Lily Brown","David Moore","Susan Taylor","Mike Jones","Tom Hill")
name_students

name_courses_legal_age <- c("TIC","Accounting","Psychology","Ethics","Legal_Age")
name_courses_legal_age
```
2.2
```{r}

colnames(student_matrix) <- name_courses_legal_age
rownames(student_matrix) <- name_students

student_matrix

```
3.rowSum, Cbind
```{r}
student_matrix[1:5,1:4]

Tgrades <- rowSums(student_matrix[1:5,1:4])
                   
colSums(student_matrix)

Tgrades

total_grade_student <- c(Tgrades)
total_grade_student


```
3.2
```{r}
result_student <- cbind(student_matrix,total_grade_student)

result_student
```

4. seleccionando elementos de una matriz 
```{r}
selected_elements <- result_student[c(1,3,5),c(2,4)]
selected_elements
```
5 Data Frames 
```{r}
students_grades_df <- data.frame(result_student)
students_grades_df

subset(students_grades_df, subset = Accounting>80 & Legal_Age ==TRUE)

```
6 Funciones, condicionales y bucles

```{r}
students_projection <- function(result_student){
  
  for(i in 1:nrow(result_student)){
  for(j in 1:ncol(result_student[1:5,1:4])){
    print(paste("on row", i, "and colum", j, "the board contains", result_student[i,j]))
  }
}
  
}

students_projection(result_student)

```
6.2, 6.3

```{r}

students_projection <- function(result_student){
  
  for(i in 1:nrow(result_student)){
  for(j in 1:ncol(result_student[1:5,1:4])){
    
    if(result_student[i,j] <= 45){
      print("student at risk")
    }else if (result_student[i,j] > 45 | result_student[i,j] < 61){
      print("student may be approved")
    }else if (result_student[i,j] >= 61){
      print("student approved")
    } else{
      print("NT")
    }
  }
}
  
}
 
```
7 data frames y lapply

```{r}
index_education <- function(grade){
  
  (1+(grade/100))/100
  
}

index_education(1)


```
7.2

```{r}

students_grades_df[,1:4]

all_student_grade <- students_grades_df[,1:4]
all_student_grade
```

7.3
```{r}

lapply(all_student_grade, index_education)

```
8. Math Utilities 
```{r}

students_grades_df[1:5,1:4]

colMeans(students_grades_df[1:4])


score_mean <- colMeans(students_grades_df[1:4])

score_mean
```

